---
# file: .travis.yml

sudo: required
language: python
services:
  - docker
env:
  global:
    - ROLE=kubectl
  matrix:
    - TOXENV=py27-ansible22
    - TOXENV=py27-ansible23
    - TOXENV=py27-ansible24
    - TOXENV=py27-ansible25
    - TOXENV=py27-ansible26
matrix:
  allow_failures:
    - env: TOXENV=py27-ansible26

install:
  - ln -s  $(basename $PWD) ../${ROLE}
  - pip install tox-travis
script:
  - tox
