---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        kubectl_release: v1.10.1
  lint:
    name: ansible-lint
scenario:
  name: custom_release
verifier:
  name: goss
  lint:
    name: yamllint
